"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { createClient } from "@/lib/supabase/client";
import { uploadFile } from "@/lib/storage/uploadFile";
import type { ExpenseFormValues } from "@/types/financial";

type View = "dashboard" | "expenses" | "categories" | "vendors" | "reports" | "expense-form" | "expense-detail";
const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value || 0);
const initial: ExpenseFormValues = { date: new Date().toISOString().slice(0,10), category_id:"", vendor_id:"", customer_id:"", job_id:"", employee_id:"", description:"", amount:"", payment_method:"Cash", status:"Paid", receipt_url:"", notes:"" };

export default function FinancialsClient({ view, expenseId }: { view: View; expenseId?: string }) {
  const supabase = useMemo(() => createClient(), []);
  const [expenses, setExpenses] = useState<any[]>([]), [categories, setCategories] = useState<any[]>([]), [vendors, setVendors] = useState<any[]>([]), [jobs, setJobs] = useState<any[]>([]), [customers, setCustomers] = useState<any[]>([]);
  const [loading, setLoading] = useState(true), [query, setQuery] = useState(""), [form, setForm] = useState(initial), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const [category, setCategory] = useState({ name:"", group_name:"Other", description:"" }); const [vendor, setVendor] = useState({ name:"", company:"", phone:"", email:"", address:"", category:"", notes:"" });
  useEffect(() => { void load(); }, []);
  async function load() {
    setLoading(true);
    const [expenseResult, categoryResult, vendorResult, jobResult, customerResult] = await Promise.all([
      supabase.from("expenses").select("*, category:expense_categories(name,group_name), vendor:vendors(name,company), job:jobs(job_number,title), customer:customers(first_name,last_name)").order("date", { ascending:false }),
      supabase.from("expense_categories").select("*").order("group_name").order("name"), supabase.from("vendors").select("*").order("name"),
      supabase.from("jobs").select("id,job_number,title").order("created_at", { ascending:false }), supabase.from("customers").select("id,first_name,last_name").order("first_name")
    ]);
    setExpenses(expenseResult.data ?? []); setCategories(categoryResult.data ?? []); setVendors(vendorResult.data ?? []); setJobs(jobResult.data ?? []); setCustomers(customerResult.data ?? []);
    if (expenseId) { const record = expenseResult.data?.find((item) => item.id === expenseId); if (record) setForm({ date:record.date, category_id:record.category_id ?? "", vendor_id:record.vendor_id ?? "", customer_id:record.customer_id ?? "", job_id:record.job_id ?? "", employee_id:record.employee_id ?? "", description:record.description, amount:String(record.amount), payment_method:record.payment_method, status:record.status, receipt_url:record.receipt_url ?? "", notes:record.notes ?? "" }); }
    setLoading(false);
  }
  const filtered = expenses.filter((item) => `${item.expense_number} ${item.description} ${item.vendor?.name ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const totalExpenses = expenses.reduce((sum,item) => sum + Number(item.amount),0); const paidInvoices = 0;
  const monthly = Array.from({length:6},(_,i) => { const d=new Date(); d.setMonth(d.getMonth()-5+i); const key=d.toISOString().slice(0,7); return { month:d.toLocaleString("en-US",{month:"short"}), expenses:expenses.filter(e=>e.date?.slice(0,7)===key).reduce((s,e)=>s+Number(e.amount),0), revenue:0 }; });
  const categoriesData = categories.map(c=>({name:c.name,value:expenses.filter(e=>e.category_id===c.id).reduce((s,e)=>s+Number(e.amount),0)})).filter(x=>x.value); const colors=["#2563eb","#0ea5e9","#6366f1","#f59e0b","#10b981"];
  async function saveExpense(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); const payload={...form, amount:Number(form.amount), category_id:form.category_id||null,vendor_id:form.vendor_id||null,customer_id:form.customer_id||null,job_id:form.job_id||null,employee_id:form.employee_id||null,receipt_url:form.receipt_url||null}; const result=expenseId ? await supabase.from("expenses").update(payload).eq("id",expenseId) : await supabase.from("expenses").insert({...payload, expense_number:`EXP-${String(Date.now()).slice(-5)}`}); setSaving(false); if(result.error) return setError(result.error.message); location.assign("/admin/financials/expenses"); }
  async function uploadReceipt(file?: File) { if (!file) return; try { const uploaded=await uploadFile({bucket:"expense-receipts",folder:"receipts",file}); setForm(p=>({...p,receipt_url:uploaded.path})); } catch(err:any) { setError(err.message); } }
  async function createCategory(e:React.FormEvent) { e.preventDefault(); const r=await supabase.from("expense_categories").insert(category); if(r.error) setError(r.error.message); else { setCategory({name:"",group_name:"Other",description:""}); load(); } }
  async function createVendor(e:React.FormEvent) { e.preventDefault(); const r=await supabase.from("vendors").insert(vendor); if(r.error) setError(r.error.message); else { setVendor({name:"",company:"",phone:"",email:"",address:"",category:"",notes:""}); load(); } }
  if (loading) return <div className="p-8 text-slate-500">Loading financial data…</div>;
  if (view === "dashboard" || view === "reports") return <div className="mx-auto max-w-7xl space-y-6 px-6 py-8"><header><h1 className="text-3xl font-bold text-slate-900">{view === "reports" ? "Financial Reports" : "Financial Dashboard"}</h1><p className="mt-1 text-slate-500">Revenue, costs, profitability, and financial performance.</p></header><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Gross Revenue",0],["Total Costs",totalExpenses],["Net Profit",-totalExpenses],["Profit Margin",0]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{String(label).includes("Margin")?"0.0%":currency(Number(value))}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><Chart title="Revenue vs Expenses"><BarChart data={monthly}><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="revenue" fill="#2563eb"/><Bar dataKey="expenses" fill="#f59e0b"/></BarChart></Chart><Chart title="Expenses by Category"><PieChart><Pie data={categoriesData} dataKey="value" nameKey="name" outerRadius={105}>{categoriesData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></Chart></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-900">{view === "reports" ? "Job Profitability & Vendor Spending" : "Monthly Expense Trend"}</h2><table className="mt-4 min-w-full text-sm"><thead className="text-left text-slate-500"><tr><th>Job / Vendor</th><th>Revenue</th><th>Costs</th><th>Profit</th></tr></thead><tbody>{jobs.slice(0,10).map(job=>{const cost=expenses.filter(e=>e.job_id===job.id).reduce((s,e)=>s+Number(e.amount),0);return <tr key={job.id} className="border-t"><td className="py-3">{job.job_number} · {job.title}</td><td>$0.00</td><td>{currency(cost)}</td><td>{currency(-cost)}</td></tr>})}</tbody></table></div></div>;
  if (view === "categories" || view === "vendors") { const isCategory=view==="categories"; return <div className="mx-auto max-w-7xl space-y-6 px-6 py-8"><h1 className="text-3xl font-bold">{isCategory?"Expense Categories":"Vendors / Payees"}</h1><div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={isCategory?createCategory:createVendor} className="space-y-3 rounded-2xl border bg-white p-6 shadow-sm">{isCategory?<><Input label="Name" value={category.name} onChange={v=>setCategory({...category,name:v})}/><Input label="Group" value={category.group_name} onChange={v=>setCategory({...category,group_name:v})}/></>:<><Input label="Name" value={vendor.name} onChange={v=>setVendor({...vendor,name:v})}/><Input label="Company" value={vendor.company} onChange={v=>setVendor({...vendor,company:v})}/><Input label="Email" value={vendor.email} onChange={v=>setVendor({...vendor,email:v})}/><Input label="Phone" value={vendor.phone} onChange={v=>setVendor({...vendor,phone:v})}/></>}<button className="rounded-xl bg-blue-600 px-4 py-2 font-medium text-white">Add {isCategory?"Category":"Vendor"}</button></form><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><table className="min-w-full text-sm"><tbody>{(isCategory?categories:vendors).map(x=><tr className="border-b" key={x.id}><td className="p-4 font-medium">{x.name}</td><td className="p-4 text-slate-500">{x.group_name ?? x.company ?? "—"}</td><td className="p-4 text-slate-500">{x.email ?? ""}</td></tr>)}</tbody></table></div></div></div>; }
  if (view === "expense-form") return <div className="mx-auto max-w-4xl px-6 py-8"><h1 className="mb-6 text-3xl font-bold">{expenseId?"Edit Expense":"New Expense"}</h1><form onSubmit={saveExpense} className="grid gap-5 rounded-2xl border bg-white p-6 shadow-sm md:grid-cols-2"><Input label="Description" value={form.description} onChange={v=>setForm({...form,description:v})}/><Input label="Amount" type="number" value={form.amount} onChange={v=>setForm({...form,amount:v})}/><Input label="Date" type="date" value={form.date} onChange={v=>setForm({...form,date:v})}/><Select label="Category" value={form.category_id} onChange={v=>setForm({...form,category_id:v})} items={categories.map(x=>[x.id,`${x.group_name} · ${x.name}`])}/><Select label="Vendor" value={form.vendor_id} onChange={v=>setForm({...form,vendor_id:v})} items={vendors.map(x=>[x.id,x.name])}/><Select label="Job" value={form.job_id} onChange={v=>setForm({...form,job_id:v})} items={jobs.map(x=>[x.id,`${x.job_number} · ${x.title}`])}/><Select label="Status" value={form.status} onChange={v=>setForm({...form,status:v as any})} items={[["Paid","Paid"],["Pending","Pending"],["Reimbursed","Reimbursed"]]}/><Select label="Payment Method" value={form.payment_method} onChange={v=>setForm({...form,payment_method:v as any})} items={[["Cash","Cash"],["Credit Card","Credit Card"],["Bank Transfer","Bank Transfer"],["Check","Check"]]}/><label className="block text-sm font-medium">Receipt<input type="file" accept="image/*,application/pdf" onChange={e=>uploadReceipt(e.target.files?.[0])} className="mt-2 block w-full"/></label><label className="block text-sm font-medium md:col-span-2">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-2 w-full rounded-xl border p-3" rows={4}/></label>{error&&<p className="text-red-600 md:col-span-2">{error}</p>}<div className="md:col-span-2"><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 font-medium text-white">{saving?"Saving…":"Save Expense"}</button></div></form></div>;
  if (view === "expense-detail") { const item=expenses.find(x=>x.id===expenseId); if(!item)return <div className="p-8">Expense not found.</div>; return <div className="mx-auto max-w-4xl space-y-6 px-6 py-8"><div className="flex justify-between"><div><h1 className="text-3xl font-bold">{item.expense_number}</h1><p className="text-slate-500">{item.description}</p></div><Link className="rounded-xl bg-blue-600 px-4 py-2 text-white" href={`/admin/financials/expenses/${item.id}/edit`}>Edit</Link></div><div className="grid gap-4 rounded-2xl border bg-white p-6 shadow-sm md:grid-cols-2"><p><b>Amount:</b> {currency(Number(item.amount))}</p><p><b>Status:</b> {item.status}</p><p><b>Category:</b> {item.category?.name ?? "—"}</p><p><b>Vendor:</b> {item.vendor?.name ?? "—"}</p><p><b>Job:</b> {item.job?.job_number ?? "—"}</p>{item.receipt_url&&<p><a className="text-blue-600" href={item.receipt_url}>View receipt</a></p>}</div></div>; }
  return <div className="mx-auto max-w-7xl space-y-6 px-6 py-8"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">Expenses</h1><p className="text-slate-500">Track costs, receipts, vendors, and project spending.</p></div><Link href="/admin/financials/expenses/new" className="rounded-xl bg-blue-600 px-4 py-3 font-medium text-white">New Expense</Link></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search expenses" className="w-full max-w-md rounded-xl border p-3"/><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Expense</th><th>Date</th><th>Category</th><th>Vendor</th><th>Amount</th><th>Status</th></tr></thead><tbody>{filtered.slice(0,25).map(item=><tr key={item.id} className="border-t hover:bg-slate-50"><td className="p-4"><Link className="font-medium text-blue-700" href={`/admin/financials/expenses/${item.id}`}>{item.expense_number}</Link><div className="text-slate-500">{item.description}</div></td><td>{item.date}</td><td>{item.category?.name ?? "—"}</td><td>{item.vendor?.name ?? "—"}</td><td>{currency(Number(item.amount))}</td><td>{item.status}</td></tr>)}</tbody></table></div></div>;
}
function Chart({title,children}:{title:string;children:React.ReactElement}) { return <div className="h-80 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-900">{title}</h2><div className="mt-4 h-60"><ResponsiveContainer>{children}</ResponsiveContainer></div></div>; }
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}) { return <label className="block text-sm font-medium">{label}<input required={label==="Name"||label==="Description"||label==="Amount"} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label>; }
function Select({label,value,onChange,items}:{label:string;value:string;onChange:(v:string)=>void;items:string[][]}) { return <label className="block text-sm font-medium">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">None</option>{items.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label>; }
