import Link from "next/link";
import { notFound } from "next/navigation";

import { getPortalDashboard } from "@/lib/portal/data";

const money = (value: number | null) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value ?? 0));

export default async function CustomerPortalPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const portal = await getPortalDashboard(token);
  if (!portal) notFound();
  const upcoming = portal.jobs.find((job) => job.scheduled_date && new Date(`${job.scheduled_date}T00:00:00`) >= new Date());
  const active = portal.jobs.filter((job) => !["Completed", "Cancelled"].includes(job.status ?? "")).length;

  return <main className="min-h-screen bg-slate-50 py-8"><div className="mx-auto max-w-6xl space-y-6 px-4 sm:px-6"><header className="rounded-2xl bg-slate-950 p-7 text-white shadow-sm"><p className="text-sm font-semibold tracking-[0.2em] text-blue-300">XAREON GROUP</p><h1 className="mt-2 text-3xl font-bold">Welcome, {portal.customer.first_name} {portal.customer.last_name}</h1><p className="mt-2 text-slate-300">Your projects, documents, and account updates in one secure place.</p></header>
    <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Active Projects</p><p className="mt-1 text-3xl font-bold">{active}</p></div><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Outstanding Balance</p><p className="mt-1 text-3xl font-bold">{money(portal.invoices.reduce((sum, invoice) => sum + Number(invoice.balance_due ?? 0), 0))}</p></div><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Upcoming Appointment</p><p className="mt-1 font-semibold">{upcoming ? `${upcoming.title ?? "Scheduled service"} · ${new Date(`${upcoming.scheduled_date}T00:00:00`).toLocaleDateString()}` : "No appointment scheduled"}</p></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Your Projects</h2><div className="mt-4 space-y-3">{portal.jobs.length ? portal.jobs.map((job) => <div key={job.id} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{job.title ?? "Service project"}</p><p className="text-sm text-slate-500">{job.job_number ?? "Job"}{job.scheduled_date ? ` · ${new Date(`${job.scheduled_date}T00:00:00`).toLocaleDateString()}` : ""}</p>{job.service_address && <p className="mt-1 text-sm text-slate-500">{job.service_address}</p>}</div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{job.status ?? "Scheduled"}</span></div></div>) : <p className="text-sm text-slate-500">No projects have been scheduled yet.</p>}</div></div>
      <div className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Project Activity</h2><div className="mt-4 space-y-4">{portal.activity.length ? portal.activity.map((event) => <div key={event.id} className="border-l-2 border-blue-500 pl-4"><p className="font-medium">{event.title}</p><p className="text-sm text-slate-500">{event.description}</p><p className="mt-1 text-xs text-slate-400">{new Date(event.created_at).toLocaleString()}</p></div>) : <p className="text-sm text-slate-500">Updates will appear here as your project progresses.</p>}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-3"><PortalList title="Estimates" empty="No estimates available." items={portal.estimates.map((item) => ({ id: item.id, label: `Estimate #${item.estimate_number}`, detail: `${item.status} · ${money(item.total)}`, href: `/portal/${token}/estimate/${item.id}` }))} /><PortalList title="Contracts" empty="No contracts available." items={portal.contracts.map((item) => ({ id: item.id, label: `Contract #${item.contract_number ?? "Pending"}`, detail: item.status ?? "Draft", href: `/portal/${token}/contract/${item.id}` }))} /><PortalList title="Invoices" empty="No invoices available." items={portal.invoices.map((item) => ({ id: item.id, label: `Invoice #${item.invoice_number}`, detail: `${money(item.balance_due)} due`, href: `/portal/${token}/invoice/${item.id}` }))} /></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Documents</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{portal.documents.length ? portal.documents.map((document) => <Link key={document.id} href={`/portal/${token}/documents/${document.id}`} className="rounded-lg border p-4 text-sm transition hover:border-blue-400 hover:bg-blue-50"><p className="font-semibold text-slate-800">{document.title}</p><p className="mt-1 capitalize text-slate-500">{document.document_type.replace(/_/g, " ")}</p></Link>) : <p className="text-sm text-slate-500">No documents are available yet.</p>}</div></section>
  </div></main>;
}

function PortalList({ title, empty, items }: { title: string; empty: string; items: { id: string; label: string; detail: string; href: string }[] }) {
  return <div className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 space-y-3">{items.length ? items.map((item) => <Link key={item.id} href={item.href} className="block rounded-lg border p-3 transition hover:border-blue-400 hover:bg-blue-50"><p className="font-semibold">{item.label}</p><p className="text-sm text-slate-500">{item.detail}</p></Link>) : <p className="text-sm text-slate-500">{empty}</p>}</div></div>;
}
