import Link from "next/link";
import { notFound } from "next/navigation";
import { getPortalInvoice } from "@/lib/portal/data";
import { PaymentButton } from "@/components/portal/PaymentButton";

export default async function PortalInvoicePage({ params }: { params: Promise<{ token: string; id: string }> }) {
  const { token, id } = await params;
  const data = await getPortalInvoice(token, id);
  if (!data) notFound();
  const money = (value: number | null) => `$${Number(value ?? 0).toFixed(2)}`;
  return <main className="min-h-screen bg-slate-50 py-8"><article className="mx-auto max-w-4xl space-y-6 px-4"><Link href={`/portal/${token}`} className="text-sm font-medium text-blue-700">← Back to portal</Link><section className="rounded-2xl bg-white p-7 shadow-sm"><p className="text-sm font-semibold tracking-[0.15em] text-blue-700">XAREON GROUP</p><h1 className="mt-2 text-3xl font-bold">Invoice #{data.invoice.invoice_number}</h1><p className="mt-2 text-slate-600">Due {data.invoice.due_date ? new Date(`${data.invoice.due_date}T00:00:00`).toLocaleDateString() : "on receipt"}</p></section><section className="overflow-hidden rounded-2xl bg-white shadow-sm"><table className="w-full text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-4">Service</th><th className="p-4">Qty</th><th className="p-4 text-right">Total</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id} className="border-t"><td className="p-4">{item.description}</td><td className="p-4">{item.quantity} {item.unit}</td><td className="p-4 text-right">{money(item.total)}</td></tr>)}</tbody></table><div className="ml-auto max-w-sm space-y-2 p-5"><div className="flex justify-between"><span>Total</span><span>{money(data.invoice.total)}</span></div><div className="flex justify-between"><span>Paid</span><span>{money(data.invoice.amount_paid)}</span></div><div className="flex justify-between border-t pt-2 text-lg font-bold text-blue-800"><span>Balance Due</span><span>{money(data.invoice.balance_due)}</span></div></div></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Payment History</h2><div className="mt-4 space-y-3">{data.payments.length ? data.payments.map((payment) => <div key={payment.id} className="flex justify-between border-b pb-3 text-sm"><span>{payment.payment_date ? new Date(`${payment.payment_date}T00:00:00`).toLocaleDateString() : "—"} · {payment.payment_method ?? "Payment"}</span><span className="font-semibold">{money(payment.amount)}</span></div>) : <p className="text-sm text-slate-500">No payments have been recorded.</p>}</div><div className="mt-5"><PaymentButton balanceDue={data.invoice.balance_due} invoiceId={data.invoice.id} portalToken={token} /></div></section></article></main>;
}
