-- Baseline schema reconstructed from the production application. Apply to a fresh
-- Supabase project before subsequent migrations; do not run against an unknown live
-- database without first comparing it to the schema snapshot.
create extension if not exists pgcrypto;
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null, email text, phone text, address text, city text, state text, zip text, notes text, status text default 'Active', archived_at timestamptz, portal_token uuid unique default gen_random_uuid(), portal_created_at timestamptz default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.employees (id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null, email text, phone text, role text, status text default 'Active', hourly_rate numeric(12,2), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.estimates (id uuid primary key default gen_random_uuid(), estimate_number text unique not null, customer_id uuid references public.customers(id) on delete set null, status text not null default 'Draft', issue_date date, expiration_date date, subtotal numeric(12,2) not null default 0, tax_rate numeric(8,4) not null default 0, tax numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, total numeric(12,2) not null default 0, notes text, terms text, signature_token uuid unique default gen_random_uuid(), signature_status text default 'Pending', signed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.estimate_items (id uuid primary key default gen_random_uuid(), estimate_id uuid not null references public.estimates(id) on delete cascade, description text not null, quantity numeric(12,2) not null default 1, unit text, unit_price numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, taxable boolean not null default true, total numeric(12,2) not null default 0, sort_order integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.jobs (id uuid primary key default gen_random_uuid(), job_number text unique not null, customer_id uuid references public.customers(id) on delete set null, estimate_id uuid references public.estimates(id) on delete set null, invoice_id uuid, assigned_employee_id uuid references public.employees(id) on delete set null, title text not null, description text, status text not null default 'Scheduled', priority text default 'Normal', scheduled_date date, start_time time, end_time time, service_address text, customer_phone text, notes text, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.invoices (id uuid primary key default gen_random_uuid(), invoice_number text unique not null, customer_id uuid references public.customers(id) on delete set null, estimate_id uuid references public.estimates(id) on delete set null, job_id uuid references public.jobs(id) on delete set null, status text not null default 'Draft', issue_date date, due_date date, subtotal numeric(12,2) not null default 0, tax numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, total numeric(12,2) not null default 0, amount_paid numeric(12,2) not null default 0, balance_due numeric(12,2) not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.jobs add constraint jobs_invoice_id_fkey foreign key (invoice_id) references public.invoices(id) on delete set null;
create table if not exists public.invoice_items (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, description text not null, quantity numeric(12,2) not null default 1, unit text, unit_price numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, taxable boolean not null default true, total numeric(12,2) not null default 0, sort_order integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, amount numeric(12,2) not null check(amount>0), payment_method text, payment_date timestamptz not null default now(), reference_number text, notes text, created_at timestamptz not null default now());
create table if not exists public.contracts (id uuid primary key default gen_random_uuid(), contract_number text unique not null, customer_id uuid references public.customers(id) on delete set null, estimate_id uuid references public.estimates(id) on delete set null, job_id uuid references public.jobs(id) on delete set null, title text, status text not null default 'Draft', terms text, scope_of_work text, payment_terms text, warranty text, notes text, signature_token uuid unique default gen_random_uuid(), signed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.customer_documents (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, document_type text, title text not null, file_url text not null, created_at timestamptz not null default now());
create table if not exists public.job_photos (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs(id) on delete cascade, image_url text not null, caption text, created_at timestamptz not null default now());
create table if not exists public.customer_activity (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, activity_type text not null, title text not null, description text, created_at timestamptz not null default now());
create table if not exists public.sequences (id uuid primary key default gen_random_uuid(), type text unique not null, current_value integer not null default 0, updated_at timestamptz not null default now());
create table if not exists public.user_roles (user_id uuid primary key references auth.users(id) on delete cascade, role text not null check(role in ('owner','admin','manager','employee','contractor','customer')), customer_id uuid references public.customers(id) on delete set null, employee_id uuid references public.employees(id) on delete set null, created_at timestamptz not null default now());
create or replace function public.current_role() returns text language sql stable security definer set search_path=public as $$select role from public.user_roles where user_id=auth.uid()$$;
create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$select coalesce(public.current_role() in ('owner','admin','manager','employee','contractor'),false)$$;
create or replace function public.can_manage_financials() returns boolean language sql stable security definer set search_path=public as $$select coalesce(public.current_role() in ('owner','admin','manager'),false)$$;
alter table public.customers enable row level security; alter table public.estimates enable row level security; alter table public.jobs enable row level security; alter table public.invoices enable row level security; alter table public.payments enable row level security; alter table public.contracts enable row level security; alter table public.customer_documents enable row level security;
create policy "staff customers" on public.customers for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "customer own record" on public.customers for select to authenticated using (id=(select customer_id from public.user_roles where user_id=auth.uid()));
create policy "staff estimates" on public.estimates for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff jobs" on public.jobs for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff invoices" on public.invoices for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff payments" on public.payments for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff contracts" on public.contracts for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff documents" on public.customer_documents for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "customer own invoices" on public.invoices for select to authenticated using (customer_id=(select customer_id from public.user_roles where user_id=auth.uid()));
create policy "customer own estimates" on public.estimates for select to authenticated using (customer_id=(select customer_id from public.user_roles where user_id=auth.uid()));
create policy "customer own contracts" on public.contracts for select to authenticated using (customer_id=(select customer_id from public.user_roles where user_id=auth.uid()));
create index if not exists customers_portal_token_idx on public.customers(portal_token); create index if not exists estimates_customer_id_idx on public.estimates(customer_id); create index if not exists jobs_customer_id_idx on public.jobs(customer_id); create index if not exists invoices_customer_id_idx on public.invoices(customer_id); create index if not exists invoices_job_id_idx on public.invoices(job_id); create index if not exists payments_invoice_id_idx on public.payments(invoice_id);
